name: Health Check

on: 
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:

  ping:
    runs-on: ubuntu-18.04
    steps:
      - name: curl actuator
        id: ping
        run: |
          echo "::set-output name=status::http://$(curl ${{ secrets.VDS_ADDRESS }}:8080/api/actuator/health)"

      - name: health check
        run: |
          if [[ ${{ steps.ping.outputs.status }} != *"UP"* ]]; then
            echo "health check is failed"
            exit 1
          fi
          echo "It's OK"
